# Generated by Django 2.2.19 on 2023-03-08 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(help_text='Как к Вам обращаться', max_length=200, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фотография')),
                ('age', models.CharField(choices=[('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59'), ('60', '60'), ('61', '61'), ('62', '62'), ('63', '63'), ('64', '64'), ('65', '65'), ('66', '66'), ('67', '67'), ('68', '68'), ('69', '69'), ('70', '70')], default=' ', help_text='Сколько вам лет', max_length=20, verbose_name='Ваш возраст')),
                ('city', models.CharField(choices=[('Казахстан', (('Астана', 'Астана'), ('Алмата', 'Алмата'), ('Барнаул', 'Барнаул'), ('Караганда', 'Караганда'), ('Павлодар', 'Павлодар'), ('Темиртау', 'Темиртау'), ('Экибастуз', 'Экибастуз')))], default=' ', help_text='Добавьте город проживания', max_length=30, verbose_name='Ваш город')),
                ('text', models.TextField(help_text='Добавьте цель пребывания на сайте', verbose_name='Ваша цель')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name_plural': 'Анкеты',
            },
        ),
    ]
